-- ==========================================================
-- INIT SCRIPT — PostgreSQL 18 + Vietnamese Collation (ICU)
-- Tự động chạy khi container db khởi tạo lần đầu
-- ==========================================================

-- Tạo ICU collation cho tiếng Việt (không dấu, không phân biệt hoa/thường)
-- Dùng cho full-text search và sắp xếp
CREATE COLLATION IF NOT EXISTS vi_ci_ai (
    PROVIDER = icu,
    LOCALE = 'vi-VN-x-icu',
    DETERMINISTIC = false
);

-- ==========================================================
-- 1. DANH MỤC / MÓN ĂN / TOPPING
-- ==========================================================

CREATE TABLE categories (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL COLLATE vi_ci_ai,
    description VARCHAR(255) COLLATE vi_ci_ai,
    image_url VARCHAR(500),
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE menu_items (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category_id INT,
    name VARCHAR(100) NOT NULL COLLATE vi_ci_ai,
    description VARCHAR(500) COLLATE vi_ci_ai,
    price DECIMAL(10,0) NOT NULL,
    image_url VARCHAR(500),
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
);

CREATE TABLE addons (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL COLLATE vi_ci_ai,
    price DECIMAL(10,0) NOT NULL DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ==========================================================
-- 2. MÓN ĂN ↔ TOPPING
-- ==========================================================

CREATE TABLE menu_item_addons (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    menu_item_id INT NOT NULL,
    addon_id INT NOT NULL,
    price_override DECIMAL(10,0),
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (menu_item_id) REFERENCES menu_items(id) ON DELETE CASCADE,
    FOREIGN KEY (addon_id) REFERENCES addons(id) ON DELETE CASCADE,
    CONSTRAINT UQ_menu_item_addon UNIQUE (menu_item_id, addon_id)
);

-- ==========================================================
-- 3. COMBO
-- ==========================================================

CREATE TABLE combos (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL COLLATE vi_ci_ai,
    combo_price DECIMAL(10,0) NOT NULL,
    description VARCHAR(500) COLLATE vi_ci_ai,
    image_url VARCHAR(500),
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE combo_items (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    combo_id INT NOT NULL,
    menu_item_id INT NOT NULL,
    quantity INT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (combo_id) REFERENCES combos(id) ON DELETE CASCADE,
    FOREIGN KEY (menu_item_id) REFERENCES menu_items(id) ON DELETE CASCADE,
    CONSTRAINT UQ_combo_item UNIQUE (combo_id, menu_item_id)
);

-- ==========================================================
-- 4. GIẢM GIÁ
-- ==========================================================

CREATE TABLE discounts (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL COLLATE vi_ci_ai,
    type VARCHAR(10) NOT NULL CHECK (type IN ('percent', 'amount')),
    value DECIMAL(10,2) NOT NULL,
    max_discount_amount DECIMAL(10,0),
    min_order_amount DECIMAL(10,0) DEFAULT 0,
    usage_limit INT,
    used_count INT DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    start_date TIMESTAMP,
    end_date TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ==========================================================
-- 5. NGUỒN ĐƠN (Bàn / Online)
-- ==========================================================

CREATE TABLE sources (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL COLLATE vi_ci_ai,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ==========================================================
-- 6. PHÂN QUYỀN (RBAC)
-- ==========================================================

CREATE TABLE roles (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL UNIQUE COLLATE vi_ci_ai,
    description VARCHAR(255) COLLATE vi_ci_ai,
    default_route VARCHAR(100) DEFAULT '/admin',
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE permissions (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL COLLATE vi_ci_ai,
    description VARCHAR(255) COLLATE vi_ci_ai,
    module VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE role_permissions (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    role_id INT NOT NULL,
    permission_id INT NOT NULL,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
    FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE,
    CONSTRAINT UQ_role_permission UNIQUE (role_id, permission_id)
);

-- ==========================================================
-- 7. NHÂN VIÊN
-- ==========================================================

CREATE TABLE employees (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    full_name VARCHAR(100) NOT NULL COLLATE vi_ci_ai,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(100),
    phone VARCHAR(20),
    avatar_url VARCHAR(500),
    role_id INT NOT NULL,
    is_active BOOLEAN DEFAULT true,
    last_login TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (role_id) REFERENCES roles(id)
);

-- ==========================================================
-- 8. KHÁCH HÀNG
-- ==========================================================

CREATE TABLE customers (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    full_name VARCHAR(100) NOT NULL COLLATE vi_ci_ai,
    phone VARCHAR(20),
    email VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    avatar_url VARCHAR(500),
    points INT DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UQ_customers_phone UNIQUE (phone),
    CONSTRAINT UQ_customers_email UNIQUE (email)
);

-- ==========================================================
-- 9. ĐƠN HÀNG
-- ==========================================================

CREATE TABLE orders (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_code VARCHAR(20) NOT NULL UNIQUE,
    source_id INT,
    employee_id INT,
    customer_id INT,
    discount_id INT,
    subtotal_amount DECIMAL(10,0) DEFAULT 0,
    discount_amount DECIMAL(10,0) DEFAULT 0,
    vat_amount DECIMAL(10,0) DEFAULT 0,
    total_amount DECIMAL(10,0) DEFAULT 0,
    qr_payment_url TEXT,
    paid_at TIMESTAMP,
    status VARCHAR(20) DEFAULT 'pending'
        CHECK (status IN ('pending', 'confirmed', 'preparing', 'ready', 'served', 'paid', 'cancelled')),
    note VARCHAR(500) COLLATE vi_ci_ai,
    printed_at TIMESTAMP,
    updated_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (source_id) REFERENCES sources(id),
    FOREIGN KEY (employee_id) REFERENCES employees(id),
    FOREIGN KEY (customer_id) REFERENCES customers(id),
    FOREIGN KEY (discount_id) REFERENCES discounts(id),
    FOREIGN KEY (updated_by) REFERENCES employees(id)
);

-- ==========================================================
-- 10. CHI TIẾT ĐƠN HÀNG
-- ==========================================================

CREATE TABLE order_items (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id INT NOT NULL,
    menu_item_id INT,
    combo_id INT,
    menu_item_name VARCHAR(255) NOT NULL,
    unit_price DECIMAL(10,0) NOT NULL,
    quantity INT DEFAULT 1,
    total_price DECIMAL(10,0) NOT NULL,
    note VARCHAR(255) COLLATE vi_ci_ai,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY (menu_item_id) REFERENCES menu_items(id) ON DELETE SET NULL,
    FOREIGN KEY (combo_id) REFERENCES combos(id) ON DELETE SET NULL
);

-- ==========================================================
-- 11. LỊCH SỬ TRẠNG THÁI ĐƠN
-- ==========================================================

CREATE TABLE order_status_history (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id INT NOT NULL,
    from_status VARCHAR(20),
    to_status VARCHAR(20) NOT NULL,
    changed_by INT,
    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    note VARCHAR(500) COLLATE vi_ci_ai,
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY (changed_by) REFERENCES employees(id)
);

-- ==========================================================
-- 12. TOpping CỦA TỪNG MÓN TRONG ĐƠN
-- ==========================================================

CREATE TABLE order_item_addons (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_item_id INT NOT NULL,
    addon_id INT NOT NULL,
    addon_name VARCHAR(100) NOT NULL,
    quantity INT DEFAULT 1,
    unit_price DECIMAL(10,0) NOT NULL,
    total_price DECIMAL(10,0) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (order_item_id) REFERENCES order_items(id) ON DELETE CASCADE,
    FOREIGN KEY (addon_id) REFERENCES addons(id)
);

-- ==========================================================
-- 13. THANH TOÁN
-- ==========================================================

CREATE TABLE payments (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id INT NOT NULL,
    amount DECIMAL(10,0) NOT NULL,
    method VARCHAR(20) NOT NULL CHECK (method IN ('cash', 'qr', 'zalopay', 'momo', 'card')),
    reference_code VARCHAR(100),
    status VARCHAR(20) DEFAULT 'success'
        CHECK (status IN ('pending', 'success', 'failed', 'refunded')),
    paid_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (order_id) REFERENCES orders(id)
);

-- ==========================================================
-- 14. CÀI ĐẶT THANH TOÁN (Ngân hàng)
-- ==========================================================

CREATE TABLE payment_settings (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    bank_id VARCHAR(50) NOT NULL,
    bank_account VARCHAR(50) NOT NULL,
    bank_name VARCHAR(100) NOT NULL COLLATE vi_ci_ai,
    bank_account_name VARCHAR(200),
    template VARCHAR(20) DEFAULT 'compact2',
    is_active BOOLEAN DEFAULT true,
    is_default BOOLEAN DEFAULT false
);

CREATE UNIQUE INDEX UQ_payment_settings_default
ON payment_settings(is_default)
WHERE is_default = true;

-- ==========================================================
-- 15. BLOG
-- ==========================================================

CREATE TABLE blog_posts (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255) NOT NULL COLLATE vi_ci_ai,
    slug VARCHAR(255) NOT NULL,
    excerpt VARCHAR(500) COLLATE vi_ci_ai,
    content TEXT COLLATE vi_ci_ai,
    thumbnail_url VARCHAR(500),
    status VARCHAR(20) DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')),
    author_id INT,
    published_at TIMESTAMP,
    meta_title VARCHAR(100),
    meta_description VARCHAR(200),
    focus_keyword VARCHAR(100),
    keywords VARCHAR(500),
    canonical_url VARCHAR(500),
    og_image_url VARCHAR(500),
    reading_time INT DEFAULT 0,
    word_count INT DEFAULT 0,
    seo_score INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (author_id) REFERENCES employees(id) ON DELETE SET NULL
);

-- ==========================================================
-- 16. THẺ (Tags) cho Blog
-- ==========================================================

CREATE TABLE tags (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL COLLATE vi_ci_ai,
    slug VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255) COLLATE vi_ci_ai,
    color VARCHAR(7) DEFAULT '#f59e0b',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE blog_post_tags (
    post_id INT NOT NULL,
    tag_id INT NOT NULL,
    PRIMARY KEY (post_id, tag_id),
    FOREIGN KEY (post_id) REFERENCES blog_posts(id) ON DELETE CASCADE,
    FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
);

-- ==========================================================
-- 17. MEDIA (S3)
-- File URL trỏ tới RustFS S3: http://rustfs:9000/food-media/{folder}/{filename}
-- ==========================================================

CREATE TABLE media (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    file_name VARCHAR(255) NOT NULL,
    folder VARCHAR(100) NOT NULL DEFAULT 'misc',
    file_url VARCHAR(500) NOT NULL,
    file_type VARCHAR(50) NOT NULL,
    file_size BIGINT,
    alt_text VARCHAR(255),
    uploaded_by_employee INT,
    uploaded_by_customer INT,
    entity_type VARCHAR(50),
    entity_id INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (uploaded_by_employee) REFERENCES employees(id) ON DELETE SET NULL,
    FOREIGN KEY (uploaded_by_customer) REFERENCES customers(id) ON DELETE SET NULL
);

CREATE INDEX IX_media_folder ON media(folder);
CREATE INDEX IX_media_entity ON media(entity_type, entity_id);

-- ==========================================================
-- 18. INDEXES (Hiệu suất)
-- ==========================================================

CREATE INDEX IX_orders_status ON orders(status);
CREATE INDEX IX_orders_created_at ON orders(created_at);
CREATE INDEX IX_orders_source_id ON orders(source_id);
CREATE INDEX IX_orders_employee_id ON orders(employee_id);
CREATE INDEX IX_order_items_order_id ON order_items(order_id);
CREATE INDEX IX_order_items_menu_item_id ON order_items(menu_item_id);
CREATE INDEX IX_menu_items_category_id ON menu_items(category_id);
CREATE INDEX IX_employees_username ON employees(username);
CREATE INDEX IX_employees_role_id ON employees(role_id);
CREATE INDEX IX_discounts_code ON discounts(code);
CREATE INDEX IX_discounts_is_active ON discounts(is_active);
CREATE INDEX IX_orders_status_created_at ON orders(status, created_at);
CREATE INDEX IX_orders_source_status ON orders(source_id, status);
CREATE INDEX IX_order_items_order_menu ON order_items(order_id, menu_item_id);
CREATE INDEX IX_menu_items_category_active ON menu_items(category_id, is_active);
CREATE INDEX IX_order_status_history_order ON order_status_history(order_id, changed_at);
CREATE INDEX IX_employees_role_active ON employees(role_id, is_active);
CREATE INDEX IX_payments_order_status ON payments(order_id, status);
CREATE INDEX IX_orders_active ON orders(id) WHERE status IN ('pending', 'preparing', 'paid');
CREATE INDEX IX_payments_success ON payments(order_id) WHERE status = 'success';
CREATE INDEX IX_menu_items_active_price ON menu_items(price) WHERE is_active = true;
CREATE INDEX IX_blog_posts_slug ON blog_posts(slug);
CREATE INDEX IX_blog_posts_status ON blog_posts(status);
CREATE INDEX IX_customers_phone ON customers(phone);
CREATE INDEX IX_customers_email ON customers(email);
CREATE INDEX IX_tags_slug ON tags(slug);
CREATE INDEX IX_blog_post_tags_tag ON blog_post_tags(tag_id);

-- ============================================================
-- SEED DATA — ADMIN ROOT & PERMISSIONS
-- ============================================================

-- 1. Admin Role
INSERT INTO roles (id, name, description, is_active, created_at)
VALUES (1, 'Admin', 'Quản trị viên Root - Toàn quyền hệ thống', true, CURRENT_TIMESTAMP);

-- 2. Admin User (password: admin123)
INSERT INTO employees (id, full_name, username, password_hash, email, phone, role_id, is_active, created_at)
VALUES (
    1,
    'Root Administrator',
    'admin',
    '$2a$12$89g1rmrXs66X5vlgbx92SuY51m.jizW3DTnsys9q9OUbtIBANrl7q',
    'chipmeo2304@gmail.com',
    '0903282169',
    1,
    true,
    CURRENT_TIMESTAMP
);

-- 3. All Permissions (12 modules, 54 permissions)
INSERT INTO permissions (id, code, name, description, module, created_at) VALUES
(1, 'category.view', 'Xem danh mục', 'Có thể xem danh sách danh mục', 'category', CURRENT_TIMESTAMP),
(2, 'category.create', 'Tạo danh mục', 'Có thể tạo danh mục mới', 'category', CURRENT_TIMESTAMP),
(3, 'category.update', 'Sửa danh mục', 'Có thể sửa danh mục', 'category', CURRENT_TIMESTAMP),
(4, 'category.delete', 'Xóa danh mục', 'Có thể xóa danh mục', 'category', CURRENT_TIMESTAMP),
(5, 'menu.view', 'Xem món ăn', 'Có thể xem danh sách món', 'menu', CURRENT_TIMESTAMP),
(6, 'menu.create', 'Tạo món ăn', 'Có thể tạo món mới', 'menu', CURRENT_TIMESTAMP),
(7, 'menu.update', 'Sửa món ăn', 'Có thể sửa món', 'menu', CURRENT_TIMESTAMP),
(8, 'menu.delete', 'Xóa món ăn', 'Có thể xóa món', 'menu', CURRENT_TIMESTAMP),
(9, 'order.view', 'Xem đơn hàng', 'Có thể xem đơn', 'order', CURRENT_TIMESTAMP),
(10, 'order.create', 'Tạo đơn hàng', 'Có thể tạo đơn', 'order', CURRENT_TIMESTAMP),
(11, 'order.update', 'Cập nhật đơn', 'Có thể cập nhật trạng thái đơn', 'order', CURRENT_TIMESTAMP),
(12, 'order.delete', 'Hủy đơn hàng', 'Có thể hủy đơn', 'order', CURRENT_TIMESTAMP),
(13, 'employee.view', 'Xem nhân viên', 'Có thể xem danh sách nhân viên', 'employee', CURRENT_TIMESTAMP),
(14, 'employee.create', 'Tạo nhân viên', 'Có thể tạo nhân viên mới', 'employee', CURRENT_TIMESTAMP),
(15, 'employee.update', 'Sửa nhân viên', 'Có thể sửa thông tin nhân viên', 'employee', CURRENT_TIMESTAMP),
(16, 'employee.delete', 'Xóa nhân viên', 'Có thể xóa nhân viên', 'employee', CURRENT_TIMESTAMP),
(17, 'role.view', 'Xem vai trò', 'Có thể xem vai trò', 'role', CURRENT_TIMESTAMP),
(18, 'role.create', 'Tạo vai trò', 'Có thể tạo vai trò mới', 'role', CURRENT_TIMESTAMP),
(19, 'role.update', 'Sửa vai trò', 'Có thể sửa vai trò', 'role', CURRENT_TIMESTAMP),
(20, 'role.delete', 'Xóa vai trò', 'Có thể xóa vai trò', 'role', CURRENT_TIMESTAMP),
(21, 'discount.view', 'Xem giảm giá', 'Có thể xem mã giảm giá', 'discount', CURRENT_TIMESTAMP),
(22, 'discount.create', 'Tạo giảm giá', 'Có thể tạo mã giảm giá', 'discount', CURRENT_TIMESTAMP),
(23, 'discount.update', 'Sửa giảm giá', 'Có thể sửa mã giảm giá', 'discount', CURRENT_TIMESTAMP),
(24, 'discount.delete', 'Xóa giảm giá', 'Có thể xóa mã giảm giá', 'discount', CURRENT_TIMESTAMP),
(25, 'source.view', 'Xem nguồn đơn', 'Có thể xem danh sách nguồn đơn', 'source', CURRENT_TIMESTAMP),
(26, 'source.create', 'Tạo nguồn đơn', 'Có thể tạo nguồn đơn mới', 'source', CURRENT_TIMESTAMP),
(27, 'source.update', 'Sửa nguồn đơn', 'Có thể sửa thông tin nguồn đơn', 'source', CURRENT_TIMESTAMP),
(28, 'source.delete', 'Xóa nguồn đơn', 'Có thể xóa nguồn đơn', 'source', CURRENT_TIMESTAMP),
(29, 'addon.view', 'Xem topping', 'Có thể xem topping', 'addon', CURRENT_TIMESTAMP),
(30, 'addon.create', 'Tạo topping', 'Có thể tạo topping', 'addon', CURRENT_TIMESTAMP),
(31, 'addon.update', 'Sửa topping', 'Có thể sửa topping', 'addon', CURRENT_TIMESTAMP),
(32, 'addon.delete', 'Xóa topping', 'Có thể xóa topping', 'addon', CURRENT_TIMESTAMP),
(33, 'combo.view', 'Xem combo', 'Có thể xem combo', 'combo', CURRENT_TIMESTAMP),
(34, 'combo.create', 'Tạo combo', 'Có thể tạo combo', 'combo', CURRENT_TIMESTAMP),
(35, 'combo.update', 'Sửa combo', 'Có thể sửa combo', 'combo', CURRENT_TIMESTAMP),
(36, 'combo.delete', 'Xóa combo', 'Có thể xóa combo', 'combo', CURRENT_TIMESTAMP),
(37, 'dashboard.view', 'Xem dashboard', 'Có thể xem trang tổng quan', 'dashboard', CURRENT_TIMESTAMP),
(38, 'analytics.view', 'Xem phân tích', 'Có thể xem báo cáo và dự báo', 'analytics', CURRENT_TIMESTAMP),
(39, 'analytics.export', 'Xuất báo cáo', 'Có thể xuất file báo cáo', 'analytics', CURRENT_TIMESTAMP),
(40, 'payment.view', 'Xem cài đặt thanh toán', 'Có thể xem thông tin tài khoản ngân hàng', 'payment', CURRENT_TIMESTAMP),
(41, 'payment.update', 'Cập nhật thanh toán', 'Có thể thêm/sửa tài khoản ngân hàng', 'payment', CURRENT_TIMESTAMP),
(42, 'payment.delete', 'Xóa cài đặt thanh toán', 'Có thể xóa tài khoản ngân hàng', 'payment', CURRENT_TIMESTAMP),
(43, 'system.view', 'Xem cài đặt hệ thống', 'Có thể xem cấu hình hệ thống', 'system', CURRENT_TIMESTAMP),
(44, 'system.update', 'Cập nhật cài đặt hệ thống', 'Có thể thay đổi cấu hình hệ thống', 'system', CURRENT_TIMESTAMP),
(45, 'blog.view', 'Xem bài viết', 'Có thể xem danh sách bài viết', 'blog', CURRENT_TIMESTAMP),
(46, 'blog.create', 'Tạo bài viết', 'Có thể tạo bài viết mới', 'blog', CURRENT_TIMESTAMP),
(47, 'blog.update', 'Sửa bài viết', 'Có thể sửa bài viết', 'blog', CURRENT_TIMESTAMP),
(48, 'blog.delete', 'Xóa bài viết', 'Có thể xóa bài viết', 'blog', CURRENT_TIMESTAMP),
(49, 'customer.view', 'Xem khách hàng', 'Có thể xem danh sách khách hàng', 'customer', CURRENT_TIMESTAMP),
(50, 'customer.create', 'Tạo khách hàng', 'Có thể tạo khách hàng', 'customer', CURRENT_TIMESTAMP),
(51, 'customer.update', 'Sửa khách hàng', 'Có thể sửa thông tin khách hàng', 'customer', CURRENT_TIMESTAMP),
(52, 'customer.delete', 'Xóa khách hàng', 'Có thể xóa khách hàng', 'customer', CURRENT_TIMESTAMP),
(53, 'media.upload', 'Tải ảnh lên', 'Có thể tải ảnh lên hệ thống', 'media', CURRENT_TIMESTAMP),
(54, 'media.delete', 'Xóa ảnh', 'Có thể xóa ảnh khỏi hệ thống', 'media', CURRENT_TIMESTAMP);

-- 4. Assign all permissions to Admin role
INSERT INTO role_permissions (role_id, permission_id, is_active, created_at)
SELECT 1, id, true, CURRENT_TIMESTAMP FROM permissions;
